# -*- coding: utf-8 -*-

#-----------------------------------------------------------------------------#
# Goal is to try different parametrizations and see which ones are better at 
# fitting some target functions (found by pcw optim) or generated by path 
# sampling
#-----------------------------------------------------------------------------#