#!/bin/bash
#PBS -l walltime=00:15:00,select=1:ncpus=1:mem=2gb

cp -r $HOME/Testing/QuantumSimulation/ .
module load anaconda3/personal
source activate py36q
cd QuantumSimulation/Batch/CSpin
python run_batch.py 'Input/test_batch_extralight.txt'

mkdir -p $WORK/Res/TestBatch
cp -r Output/TestBatchLight/ $WORK/Res/TestBatch
